export const MOCK_DATA = `{
  "lessons": [
    {
      "subject": "Военная подготов",
      "title": "Военная подготовка",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "08:30",
      "dayIdx": 0,
      "weekIdx": 0,
      "duration": 95,
      "id": "Bk3YcRiSg"
    },
    {
      "subject": "Силов.эл/н.устр.",
      "title": "Силовые электронные устройства автоматики",
      "lessonType": "ЛК",
      "room": "10-415",
      "teacher": " Каранкевич А.Г.      ",
      "timeStart": "08:30",
      "dayIdx": 5,
      "weekIdx": 0,
      "duration": 95,
      "id": "Bkg2tcAjBe"
    },
    {
      "subject": "Военная подготов",
      "title": "Военная подготовка",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "10:25",
      "dayIdx": 0,
      "weekIdx": 0,
      "duration": 95,
      "id": "S1WhYcAoHx"
    },
    {
      "subject": "Проф.подг.на АЯ",
      "title": "Профессиональная подготовка на английском языке",
      "lessonType": "ПР",
      "room": "10-103",
      "teacher": " Рудницкий В.А.      ",
      "timeStart": "10:25",
      "dayIdx": 1,
      "weekIdx": 0,
      "duration": 95,
      "id": "Syz2K5RsBg"
    },
    {
      "subject": "ПТХ скваж.прод.",
      "title": "Подготовка, транспорт и хранение скважинной продукции",
      "lessonType": "ЛБ",
      "room": "10-115",
      "teacher": " Семенов Н.М.      ",
      "timeStart": "10:25",
      "dayIdx": 2,
      "weekIdx": 0,
      "duration": 95,
      "id": "ByX2YqCjBl"
    },
    {
      "subject": "МПТ",
      "title": "Микропроцессорная техника",
      "lessonType": "ЛК",
      "room": "10-415",
      "teacher": " Тутов И.А.      ",
      "timeStart": "10:25",
      "dayIdx": 3,
      "weekIdx": 0,
      "duration": 95,
      "id": "r1E3tcRiHg"
    },
    {
      "subject": "Правоведение",
      "title": "Правоведение",
      "lessonType": "ЛК",
      "room": "19-142",
      "teacher": " Гончаренко М.В.      ",
      "timeStart": "10:25",
      "dayIdx": 4,
      "weekIdx": 0,
      "duration": 95,
      "id": "ByrnY9CsBx"
    },
    {
      "subject": "Силов.эл/н.устр.",
      "title": "Силовые электронные устройства автоматики",
      "lessonType": "ЛБ",
      "room": "10-027",
      "teacher": " Каранкевич А.Г.      ",
      "timeStart": "10:25",
      "dayIdx": 5,
      "weekIdx": 0,
      "duration": 95,
      "id": "r1I2Y50sre"
    },
    {
      "subject": "Военная подготов",
      "title": "Военная подготовка",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "12:20",
      "dayIdx": 0,
      "weekIdx": 0,
      "duration": 95,
      "id": "B1P2KcAjrx"
    },
    {
      "subject": "Орг,планир.АП",
      "title": "Организация и планирование автоматизированных производств",
      "lessonType": "ПР",
      "room": "8-327",
      "teacher": " Хаперская А.В.      ",
      "timeStart": "12:20",
      "dayIdx": 1,
      "weekIdx": 0,
      "duration": 95,
      "id": "Bku2KqAiHe"
    },
    {
      "subject": "Мат.прогр,опт.си",
      "title": "Математическое программирование и оптимизация систем",
      "lessonType": "ПР",
      "room": "10-027",
      "teacher": " Воронин А.В.      ",
      "timeStart": "12:20",
      "dayIdx": 2,
      "weekIdx": 0,
      "duration": 95,
      "id": "r1tntq0jBx"
    },
    {
      "subject": "Диагн,надежн.АС",
      "title": "Диагностика и надежность автоматизированных систем",
      "lessonType": "ПР",
      "room": "10-103",
      "teacher": " Леонов С.В.      ",
      "timeStart": "12:20",
      "dayIdx": 3,
      "weekIdx": 0,
      "duration": 95,
      "id": "HkchFq0sHl"
    },
    {
      "subject": "Военная подготов",
      "title": "Военная подготовка",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "14:15",
      "dayIdx": 0,
      "weekIdx": 0,
      "duration": 95,
      "id": "SyjnKqCoSx"
    },
    {
      "subject": "ПТХ скваж.прод.",
      "title": "Подготовка, транспорт и хранение скважинной продукции",
      "lessonType": "ЛК",
      "room": "10-415",
      "teacher": " Семенов Н.М.      ",
      "timeStart": "14:15",
      "dayIdx": 1,
      "weekIdx": 0,
      "duration": 95,
      "id": "ry3ntcCorx"
    },
    {
      "subject": "ПИЯ (русский)",
      "title": "Профессиональный иностранный язык (русский)",
      "lessonType": "ПР",
      "room": "19-428",
      "teacher": " Ефанова Л.Г.      ",
      "timeStart": "14:15",
      "dayIdx": 2,
      "weekIdx": 0,
      "duration": 95,
      "id": "ByThY5Rsre"
    },
    {
      "subject": "АТПП",
      "title": "Автоматизация технологических процессов и производств",
      "lessonType": "ЛБ",
      "room": "10-115",
      "teacher": " Журавлев Д.В.      ",
      "timeStart": "14:15",
      "dayIdx": 3,
      "weekIdx": 0,
      "duration": 95,
      "id": "rJAhF50sSg"
    },
    {
      "subject": "Физич.культура",
      "title": "Физическая культура",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "16:10",
      "dayIdx": 1,
      "weekIdx": 0,
      "duration": 95,
      "id": "SyyenKcAjSe"
    },
    {
      "subject": "Военная подготов",
      "title": "Военная подготовка",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "08:30",
      "dayIdx": 0,
      "weekIdx": 1,
      "duration": 95,
      "id": "HkeenYqCiSx"
    },
    {
      "subject": "Правоведение",
      "title": "Правоведение",
      "lessonType": "ПР",
      "room": "19-318",
      "teacher": " Гончаренко М.В.      ",
      "timeStart": "08:30",
      "dayIdx": 1,
      "weekIdx": 1,
      "duration": 95,
      "id": "Sy-xnF5Ajre"
    },
    {
      "subject": "Проф.подг.на АЯ",
      "title": "Профессиональная подготовка на английском языке",
      "lessonType": "ПР",
      "room": "10-103",
      "teacher": " Рудницкий В.А.      ",
      "timeStart": "08:30",
      "dayIdx": 2,
      "weekIdx": 1,
      "duration": 95,
      "id": "H1MlnYq0jrx"
    },
    {
      "subject": "Силов.эл/н.устр.",
      "title": "Силовые электронные устройства автоматики",
      "lessonType": "ЛБ",
      "room": "10-027",
      "teacher": " Каранкевич А.Г.      ",
      "timeStart": "08:30",
      "dayIdx": 5,
      "weekIdx": 1,
      "duration": 95,
      "id": "SkmenK5CoHg"
    },
    {
      "subject": "Военная подготов",
      "title": "Военная подготовка",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "10:25",
      "dayIdx": 0,
      "weekIdx": 1,
      "duration": 95,
      "id": "SJVl2YqRirg"
    },
    {
      "subject": "Орг,планир.АП",
      "title": "Организация и планирование автоматизированных производств",
      "lessonType": "ПР",
      "room": "НТБ-170",
      "teacher": " Хаперская А.В.      ",
      "timeStart": "10:25",
      "dayIdx": 1,
      "weekIdx": 1,
      "duration": 95,
      "id": "Syre2Y5CoBx"
    },
    {
      "subject": "ПТХ скваж.прод.",
      "title": "Подготовка, транспорт и хранение скважинной продукции",
      "lessonType": "ЛБ",
      "room": "10-115",
      "teacher": " Семенов Н.М.      ",
      "timeStart": "10:25",
      "dayIdx": 2,
      "weekIdx": 1,
      "duration": 95,
      "id": "rkIgnK9Csrg"
    },
    {
      "subject": "Орг,планир.АП",
      "title": "Организация и планирование автоматизированных производств",
      "lessonType": "ЛК",
      "room": "НТБ-365",
      "teacher": " Хаперская А.В.      ",
      "timeStart": "10:25",
      "dayIdx": 3,
      "weekIdx": 1,
      "duration": 95,
      "id": "SkDxht5Aorx"
    },
    {
      "subject": "Военная подготов",
      "title": "Военная подготовка",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "12:20",
      "dayIdx": 0,
      "weekIdx": 1,
      "duration": 95,
      "id": "BydenKqRsrg"
    },
    {
      "subject": "АТПП",
      "title": "Автоматизация технологических процессов и производств",
      "lessonType": "ЛК",
      "room": "10-415",
      "teacher": " Журавлев Д.В.      ",
      "timeStart": "12:20",
      "dayIdx": 1,
      "weekIdx": 1,
      "duration": 95,
      "id": "BkKg2YqRjBg"
    },
    {
      "subject": "МПТ",
      "title": "Микропроцессорная техника",
      "lessonType": "ЛБ",
      "room": "10-106",
      "teacher": " Тутов И.А.      ",
      "timeStart": "12:20",
      "dayIdx": 2,
      "weekIdx": 1,
      "duration": 95,
      "id": "ry9lhK5CoHe"
    },
    {
      "subject": "Диагн,надежн.АС",
      "title": "Диагностика и надежность автоматизированных систем",
      "lessonType": "ЛК",
      "room": "10-415",
      "teacher": " Леонов С.В.      ",
      "timeStart": "12:20",
      "dayIdx": 3,
      "weekIdx": 1,
      "duration": 95,
      "id": "B1ig3FqAjHl"
    },
    {
      "subject": "Военная подготов",
      "title": "Военная подготовка",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "14:15",
      "dayIdx": 0,
      "weekIdx": 1,
      "duration": 95,
      "id": "Sy2g3t9RoHl"
    },
    {
      "subject": "Мат.прогр,опт.си",
      "title": "Математическое программирование и оптимизация систем",
      "lessonType": "ЛК",
      "room": "10-418",
      "teacher": " Воронин А.В.      ",
      "timeStart": "14:15",
      "dayIdx": 1,
      "weekIdx": 1,
      "duration": 95,
      "id": "SkTe3F90jHl"
    },
    {
      "subject": "ПИЯ (русский)",
      "title": "Профессиональный иностранный язык (русский)",
      "lessonType": "ПР",
      "room": "19-428",
      "teacher": " Ефанова Л.Г.      ",
      "timeStart": "14:15",
      "dayIdx": 2,
      "weekIdx": 1,
      "duration": 95,
      "id": "BJRg2t9CjHg"
    },
    {
      "subject": "АТПП",
      "title": "Автоматизация технологических процессов и производств",
      "lessonType": "ЛБ",
      "room": "10-115",
      "teacher": " Журавлев Д.В.      ",
      "timeStart": "14:15",
      "dayIdx": 3,
      "weekIdx": 1,
      "duration": 95,
      "id": "Syk-2F90sSl"
    },
    {
      "subject": "Физич.культура",
      "title": "Физическая культура",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "16:10",
      "dayIdx": 1,
      "weekIdx": 1,
      "duration": 95,
      "id": "HJlbnF5Rsrx"
    },
    {
      "subject": "Физич.культура",
      "title": "Физическая культура",
      "lessonType": "ПР",
      "room": "",
      "teacher": " ",
      "timeStart": "16:10",
      "dayIdx": 4,
      "weekIdx": 1,
      "duration": 95,
      "id": "rybb2YcAsHl"
    }
  ], "isTwoWeeks": true, "startMonday": "2017-01-02T14:38:59.620Z"
}`;
